alwaysObtain
Garlic-Team/GCommands pull request #180
Opened 2021-09-13 15:11 UTC by S222em

**Please describe the changes this PR makes and why it should be merged:**
This PR adds an explanation for `alwaysObtain`.

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-09-13 16:34 UTC, xHyroM commented
Can you add this to https://gcommands.js.org/guide/guide/commands/additionalfeatures/ ?

2021-09-13 16:40 UTC, Caieon requested changes

2021-09-13 16:40 UTC, Caieon commented on guide/guide/questions/alwaysobtain.md
> +This example is too showcase in which cases `alwaysObtain` would be usefull:
```suggestion
This example is to showcase in which cases `alwaysObtain` would be useful:
```

2021-09-13 16:40 UTC, Caieon commented on guide/guide/questions/alwaysobtain.md
> +The `alwaysObtain` option does a simple thing. Arguments in the first message iniating the command do not count.
```suggestion
The `alwaysObtain` option does a simple thing. Arguments in the first message initiating the command do not count.
```

2021-09-14 13:04 UTC, S222em commented
> Can you add this to https://gcommands.js.org/guide/guide/commands/additionalfeatures/ ?

@xHyroM done

2021-09-14 13:58 UTC, merged