Add Polish language to message.json
Garlic-Team/GCommands pull request #23
Opened 2021-06-13 13:56 UTC by dotmyrame

2021-06-13 16:00 UTC, xHyroM commented
Can you make PR to dev branch?

2021-06-13 16:02 UTC, xHyroM requested changes
Dev branch please

2021-06-13 16:11 UTC, dotmyrame commented
yes, no problem, I'll do it as I'll be at home

2021-06-13 16:19 UTC, closed without merging

2021-06-25 14:35 UTC, xHyroM reviewed
a