Update message.json
Garlic-Team/GCommands pull request #272
Opened 2022-01-01 12:31 UTC by zVapor-Dev

**Please describe the changes this PR makes and why it should be merged:**
I added the language: Dutch to the message.json file.

**Status and versioning classification:**

2022-01-01 12:37 UTC, xHyroM commented
please change it to Garlic-Team/dev-latest branch

2022-01-02 19:08 UTC, S222em requested changes
Could you also change the branch to dev-latest?

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je moet de {PERMISSION} permissie hebben om dit command te gebruiken."
```suggestion
        "nederlands": "Je moet de {PERMISSION} permissie hebben om dit commando te gebruiken."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "De client moet de {PERMISSION} permissie hebben om dit command te gebruiken."
```suggestion
        "nederlands": "De client moet de {PERMISSION} permissie hebben om dit commando uit te voeren."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je hebt geen van de vereiste roles om dit command te kunnen gebruiken! Je hebt een van de volgende rollen nodig: {ROLES}"
```suggestion
        "nederlands": "Je hebt geen van de vereiste rollen om dit commando te kunnen gebruiken! Je hebt een van de volgende rollen nodig: {ROLES}"
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je moet {COOLDOWN} wachten voor je dat command opnieuw kan gebruiken."
```suggestion
        "nederlands": "Je moet {COOLDOWN} wachten voor je dat commando opnieuw kan gebruiken."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Het command {COMMAND} is niet gevonden!"
```suggestion
        "nederlands": "Het commando {COMMAND} is niet gevonden!"
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je kan dit command alleen gebruiken in text kanalen."
```suggestion
        "nederlands": "Je kan dit commando alleen gebruiken in text kanalen."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je kan dit command alleen gebruiken in nieuws kanalen."
```suggestion
        "nederlands": "Je kan dit commando alleen gebruiken in nieuws kanalen."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je kan dit command alleen gebruiken in threads."
```suggestion
        "nederlands": "Je kan dit commando alleen gebruiken in threads."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je kan dit command alleen gebruiken in nsfw kanalen."
```suggestion
        "nederlands": "Je kan dit commando alleen gebruiken in nsfw kanalen."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Je tijd om deze vraag te beantwoorden is op. Voer het command opnieuw uit."
```suggestion
        "nederlands": "Je tijd om deze vraag te beantwoorden is op. Voer het commando opnieuw uit."
```

2022-01-02 19:08 UTC, S222em commented on src/util/message.json
> +        "nederlands": "Kies aub een van de volgende subcommands: {choices}."
```suggestion
        "nederlands": "Kies aub een van de volgende subcommando's: {choices}."
```

2022-01-02 20:00 UTC, zVapor-Dev commented
alr I updated the suggestions and changed the branch

2022-01-02 20:38 UTC, S222em approved these changes

2022-01-02 21:00 UTC, xHyroM commented
Please resolve conflicts

2022-01-02 21:03 UTC, zVapor-Dev commented
ok done

2022-01-02 21:36 UTC, S222em commented
Something went wrong here. Make sure the branch you merge with is dev-latest and not the next branch

2022-01-02 22:25 UTC, zVapor-Dev commented
> Something went wrong here. Make sure the branch you merge with is dev-latest and not the next branch

On my end it says awaiting approval

2022-01-03 07:41 UTC, xHyroM commented
Don't edit package.json

2022-01-04 12:03 UTC, zVapor-Dev commented
You asked me to resolve the conflicts so I did. Package.json was one of them

2022-01-04 12:10 UTC, S222em requested changes
This is a merge with the package.json from the work in progress next version of commands. We can not merge it in this state. Please change the package.json to its original state

2022-01-04 12:11 UTC, zVapor-Dev commented
But this is the one from gcommands dev

2022-01-04 12:13 UTC, S222em commented
> But this is the one from gcommands dev

It's definitely not. This is the correct package.json https://github.com/Garlic-Team/GCommands/blob/latest-dev/package.json

2022-01-04 12:14 UTC, zVapor-Dev commented
I’ll have a look when I’m home

2022-01-04 12:35 UTC, zVapor-Dev commented
I should've added it now. please re-review

2022-01-04 12:41 UTC, xHyroM approved these changes

2022-01-04 13:14 UTC, S222em approved these changes

2022-01-04 13:16 UTC, merged