4.4.0
Garlic-Team/GCommands pull request #30
Opened 2021-07-06 12:23 UTC by xHyroM

2021-07-06 17:13 UTC, iZboxo approved these changes

2021-07-06 17:21 UTC, SebestikCZ approved these changes
Fine

2021-07-06 18:09 UTC, Gabe616 approved these changes
pog

2021-07-07 16:16 UTC, SebestikCZ commented on src/base/GCommands.js
> -        this.client.categories = fs.readdirSync("./" + this.cmdDir );
Get back categories!

2021-07-07 16:24 UTC, SebestikCZ requested changes
Hyro, on 240 line in GMessage.js there is an conflicting expression, replace updater.checkDjsVersion("13") with ifDjsV13!

2021-07-07 16:59 UTC, xHyroM commented on src/base/GCommands.js
> -        this.client.categories = fs.readdirSync("./" + this.cmdDir );
Okay, but I'll rename to gcategories.

2021-07-07 17:05 UTC, xHyroM commented
> 
> 
> Hyro, on 240 line in GMessage.js there is an conflicting expression, replace updater.checkDjsVersion("13") with ifDjsV13!

resolved

2021-07-07 17:16 UTC, SebestikCZ approved these changes
Thanks, and now check your DMs

2021-07-07 20:12 UTC, hernikplays approved these changes

2021-07-07 20:54 UTC, xHyroM commented on src/managers/GEventHandling.js
```suggestion
```

Can't edit attachments.

2021-07-07 20:54 UTC, xHyroM commented on src/managers/GEventHandling.js
> +                files: GPayloadResult.files
```suggestion
```

Can't edit attachments.

2021-07-07 20:54 UTC, xHyroM commented on src/structures/GMessage.js
> +                    .resolveFiles();
```suggestion
```

Can't edit attachments.

2021-07-07 20:55 UTC, xHyroM commented on src/structures/GMessage.js
> +                    .resolveFiles();
```suggestion
```

Can't edit attachments.

2021-07-07 20:55 UTC, xHyroM commented on src/structures/GMessage.js
> +                    .resolveFiles();
```suggestion
```

Can't edit attachments.

2021-07-07 20:55 UTC, xHyroM commented on src/structures/GMessage.js
> +            .resolveFiles();
```suggestion
```

Can't edit attachments.

2021-07-07 20:56 UTC, xHyroM commented on src/structures/GMessage.js
> +            files: GPayloadResult.files
```suggestion
```

Can't edit attachments.

2021-07-07 20:56 UTC, xHyroM commented on src/structures/InteractionEvent.js
```suggestion
```

Can't edit attachments.

2021-07-08 12:36 UTC, WurstMod approved these changes

2021-07-12 10:30 UTC, xHyroM commented
https://github.com/Garlic-Team/GCommands/issues/39

2021-07-13 14:57 UTC, xHyroM commented
Preparation for normal arguments.
```js
args: [
 // etc (same as slash args) https://gcommands.js.org/guide/guide/beginner/arguments.html#without-slash-group
]
```

2021-07-16 09:19 UTC, xHyroM commented on src/base/GCommands.js
> +        this.caseSensitiveCommands = Boolean(options.caseSensitiveCommands) || true
Not working, need fix

2021-07-17 18:10 UTC, iZboxo commented
I think everything is corect.

2021-07-17 18:11 UTC, iZboxo approved these changes
Everything is correct. Gcommands is best.

2021-07-17 19:06 UTC, Gabe616 approved these changes

2021-07-18 04:41 UTC, merged