feat(Command): Add category command option
Garlic-Team/GCommands pull request #437
Opened 2022-05-01 13:27 UTC by SebestikCZ

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
- This PR changes the library's interface (methods or parameters added)

2022-05-01 13:53 UTC, S222em commented
I am not sure if this should be added, as users can just extend the Command class for this feature, and with the new slash commands I don't see it getting used anyways. I'll let @xHyroM decide on this

2022-05-01 16:02 UTC, xHyroM commented
Option 1

I agree with @S222em that people can extend the command like I have in my bot for example:
```ts
import { Command, CommandOptions } from 'gcommands';

export type CommandCategory = 'management' | 'moderation' | 'utility' | 'developer';
export type ExtendedCommandOptions = CommandOptions & {
    syntax?: string;
    category?: CommandCategory;
}

export class ExtendedCommand extends Command {
	syntax?: string;
	category?: CommandCategory;
	constructor(options: ExtendedCommandOptions) {
		super(options);

		this.syntax = options.syntax;
		this.category = options.category;
	}
}
```

We could add this example to the guide. 

Option 2
Maybe we could still make some raw proper ones `options` or `data` where all the raw options you put in the command would be.

2022-05-01 16:04 UTC, S222em commented
> Option 1
> 
> 
> 
> I agree with @S222em that people can extend the command like I have in my bot for example:
> 
> ```ts
> 
> import { Command, CommandOptions } from 'gcommands';
> 
> 
> 
> export type CommandCategory = 'management' | 'moderation' | 'utility' | 'developer';
> 
> export type ExtendedCommandOptions = CommandOptions & {
> 
>     syntax?: string;
> 
>     category?: CommandCategory;
> 
> }
> 
> 
> 
> export class ExtendedCommand extends Command {
> 
> 	syntax?: string;
> 
> 	category?: CommandCategory;
> 
> 	constructor(options: ExtendedCommandOptions) {
> 
> 		super(options);
> 
> 
> 
> 		this.syntax = options.syntax;
> 
> 		this.category = options.category;
> 
> 	}
> 
> }
> 
> ```
> 
> 
> 
> We could add this example to the guide. 
> 
> 
> 
> Option 2
> 
> Maybe we could still make some raw proper ones `options` or `data` where all the raw options you put in the command would be.

Agreed

2022-05-01 16:16 UTC, SebestikCZ commented
> > Option 1
> > 
> > 
> > 
> > I agree with @S222em that people can extend the command like I have in my bot for example:
> > 
> > ```ts
> > 
> > import { Command, CommandOptions } from 'gcommands';
> > 
> > 
> > 
> > export type CommandCategory = 'management' | 'moderation' | 'utility' | 'developer';
> > 
> > export type ExtendedCommandOptions = CommandOptions & {
> > 
> >     syntax?: string;
> > 
> >     category?: CommandCategory;
> > 
> > }
> > 
> > 
> > 
> > export class ExtendedCommand extends Command {
> > 
> > 	syntax?: string;
> > 
> > 	category?: CommandCategory;
> > 
> > 	constructor(options: ExtendedCommandOptions) {
> > 
> > 		super(options);
> > 
> > 
> > 
> > 		this.syntax = options.syntax;
> > 
> > 		this.category = options.category;
> > 
> > 	}
> > 
> > }
> > 
> > ```
> > 
> > 
> > 
> > We could add this example to the guide. 
> > 
> > 
> > 
> > Option 2
> > 
> > Maybe we could still make some raw proper ones `options` or `data` where all the raw options you put in the command would be.
> 
> Agreed. @SebestikCZ can you do what hyro suggested in option 2?

I could do that, but I don't know, what do you want from me

2022-05-01 16:20 UTC, S222em commented
@SebestikCZ as hyro suggested in option 2, add a Command#options field (for Components, Plugins and Listeners as well please) where the options for the command are stored instead of command.name for example, it would became command.options.name

2022-05-01 16:23 UTC, SebestikCZ commented
okay, seems legit to make

2022-05-01 16:54 UTC, xHyroM commented
> @SebestikCZ as hyro suggested in option 2, add a Command#options field (for Components, Plugins and Listeners as well please) where the options for the command are stored, so instead of command.name, it would become command.options.name
> 
> Discord.js also uses this in their Client class for example

But we need keep this.name for example for minor change

2022-05-01 17:28 UTC, SebestikCZ commented
I comitted it to another branch reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
_once again_

2022-05-01 17:40 UTC, SebestikCZ commented
hm, a little change will be needed

2022-05-01 18:09 UTC, xHyroM requested changes

2022-05-01 18:09 UTC, xHyroM commented on src/lib/structures/Command.ts
> +				this.options = options;
Put this before zod validation

https://github.com/SebestikCZ/GCommands/blob/c890545d3ce22de37df900aaa2f86db730e89455/src/lib/structures/Command.ts#L135-L136

2022-05-01 18:16 UTC, S222em commented
@xHyroM what about removing all the options on the command level? e.g. remove `command.name` etc, so options will only reside in the `command.options` and the run method can be replaced with one that catches any errors itself, instead of doing that in the handler.

2022-05-01 18:17 UTC, xHyroM commented
> @xHyroM what about removing all the options on the command level? e.g. remove `command.name` etc, so options will only reside in the `command.options` and the run method can be replaced with one that catches any errors itself, instead of doing that in the handler.

hm, idk we want minor change now

2022-05-01 18:26 UTC, S222em commented
> > @SebestikCZ as hyro suggested in option 2, add a Command#options field (for Components, Plugins and Listeners as well please) where the options for the command are stored, so instead of command.name, it would become command.options.name
> > Discord.js also uses this in their Client class for example
> 
> But we need keep this.name (example) for minor change
> 
> Just set this.options after constructor and then valid it with zod and set this.name for example

@xHyroM shouldn't `this.options` be set after zod validated it? Zod actually transforms the value on some cases as well, and that wont be reflected into `this.options` then. Zod is also set to let any additional items trough so there should be no issue.

2022-05-02 12:56 UTC, xHyroM commented
> > > @SebestikCZ as hyro suggested in option 2, add a Command#options field (for Components, Plugins and Listeners as well please) where the options for the command are stored, so instead of command.name, it would become command.options.name
> > > Discord.js also uses this in their Client class for example
> > 
> > 
> > But we need keep this.name (example) for minor change
> > Just set this.options after constructor and then valid it with zod and set this.name for example
> 
> @xHyroM shouldn't `this.options` be set after zod validated it? Zod actually transforms the value on some cases as well, and that wont be reflected into `this.options` then. Zod is also set to let any additional items trough so there should be no issue.

ah, okay then @SebestikCZ time to revert it xd

2022-05-04 09:03 UTC, S222em requested changes

2022-05-04 09:03 UTC, S222em commented on src/lib/structures/Command.ts
> +				this.options = options || Command.defaults?;
You should merge the defaults with the options (options overwrites defaults). Be careful to not overwrite the defaults with the merged one.

2022-05-04 09:03 UTC, S222em commented on src/lib/structures/Component.ts
> +				this.options = options || Component.defaults?;
Same here

2022-05-04 09:03 UTC, S222em commented on src/lib/structures/Plugin.ts
> +	public options: Object;
This should be typed beter

2022-05-07 10:08 UTC, xHyroM commented
@SebestikCZ

2022-05-09 15:10 UTC, SebestikCZ commented
If you have ideas, how to make it right, set up commits and I will add it to this pull

2022-05-09 15:22 UTC, xHyroM commented
> If you have ideas, how to make it right, set up commits and I will add it to this pull

Just type `options` in Plugin.ts

```ts
export interface PluginOptions {
    name: string;
    run: (client: GClient) => any;
}
```

2022-05-12 15:31 UTC, S222em approved these changes

2022-05-12 15:31 UTC, xhyrom approved these changes

2022-05-12 15:32 UTC, merged